### ISSUE TITLE
Update data checklist on wiki

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1291]
Consolidate revenue monthly and annually. Update checking trends.

**Comment by Maroyafaied** [comment]
@lpgoldstein  @jennmalcolm please review the changes I made in the wiki page for the data checklist. 

https://github.com/ONRR/nrrd/wiki/Releasing-changes-to-production#updating-data-files

**Comment by lpgoldstein** [comment]
@maroya What you do think about adding some more detail to how we check the different data types? For example, for each data type in explore data - I try to check a state with different characteristics to look for mistakes - for example, an onshore state, offshore, a state with no data. Or making sure not to check just the default year. For commodities, I always check the main ones and then at least one with less production or revenue. Maybe also some more specific filters in the query tool? Maybe how we direct people to complete certain tasks in user interviews to see if we can find the data.

**Comment by Maroyafaied** [comment]
@lpgoldstein I have on the checklist, to check an offshore cards, states with no data, select different years and choose different commodities for explore data. If I missed anything please feel free to make changes.

**Comment by jennmalcolm** [comment]
@Baymatt and I are meeting later today about updating the checklist with a bit more detail on the data type, so we'll let you know our suggestions.

**Comment by Maroyafaied** [comment]
@Baymatt did you still want to suggest details for this checklist or can I close this issue?

**Comment by Baymatt** [comment]
@Maroyafaied I have a list and I'll be going over some of them in today's meeting. I'll post them on this issue soon

**Comment by Baymatt** [comment]
### Revenue
#### Homepage - Yearly Breakdown
- [ ] Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - Period - Fiscal Year
    - Period - Calendar Year
    - Breakout - Source
    - Breakout - Revenue Type
    - Breakout - Commodity
 
#### Homepage - Monthly Breakdown
- [ ] Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - Period - Most recent 12 months
    - Period - Fiscal Year
    - Period - Calendar Year
    - Breakout - Source
    - Breakout - Revenue Type
    - Breakout Commodity
 
#### Source File
- [ ] Check source file links are correct.
 
#### Explore Data - Map and Detail Card
- [ ] Select a year and select a state with data, verify information on the detail cards are correct as well as the Revenue Over Time line graph. Repeat with the latest available year.
    - Period - Calendar Year
    - Period - Fiscal Year
    - With only 2-3 commodities selected
 
- [ ] Select a year and select a county with data, verify information on the detail cards are correct as well as the Revenue Over Time line graph. Repeat with the latest available year.
    - Period - Calendar Year
    - Period - Fiscal Year
    - With only 2-3 commodities selected.
 
- [ ] Select a year and select an offshore area, verify information on the detail cards are correct as well as the Revenue Over Time line graph. Repeat with the latest available year.
    - Period - Calendar Year
    - Period - Fiscal Year
    - With only 2-3 commodities selected.
 
- [ ] Select a state and county without data and verify the expected information is displayed.

#### Explore Data - Nationwide Revenue Summary and Top Nationwide Locations
- [ ] Verify breakdowns by revenue type and source are correct as well nationwide locations for the conditions below.
    - Not current Calendar Year
    - Current Calendar Year
    - Not current Fiscal Year
    - Current Fiscal Year

#### Explore Data - Federal Revenue by Company
- [ ] Verify revenue by company information is correct for the conditions below.
    - Not current Calendar Year
    - Current Calendar Year

#### Query Data
- [ ] With a selected fiscal year range, verify the data is correct and then for the conditions below. Then repeat with a selected calendar year range.
    - One Land Type filter
    - One Revenue Type filter
    - One State
    - One Offshore Region
    - One to three Commodities
    - Clear All and change grouping

### Production
#### Homepage - Yearly Breakdown
- [ ] Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - Period - Fiscal Year
    - Period - Calendar Year
    - Commodity - Oil (bbl)
    - Commodity - Gas (mcf)
    - Commodity - Coal (tons)
 
#### Homepage - Monthly Breakdown
- [ ] Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - Period - Most recent 12 months
    - Period - Fiscal Year
    - Period - Calendar Year
    - Commodity - Oil (bbl)
    - Commodity - Gas (mcf)
    - Commodity - Coal (tons)
 
#### Source File
- [ ] Check source file links are correct.
 
#### Explore Data - Map and Detail Card
- [ ] Select a year and select a state with data, verify information on the detail cards are correct as well as the Production Over Time line graph. Repeat with the latest available year.
    - Period - Calendar Year
    - Period - Fiscal Year
    - With only 2-3 commodities selected
 
- [ ] Select a year and select a county with data, verify information on the detail cards are correct as well as the Production Over Time line graph. Repeat with the latest available year.
    - Period - Calendar Year
    - Period - Fiscal Year
    - With only 2-3 commodities selected.
 
- [ ] Select a year and select an offshore area, verify information on the detail cards are correct as well as the Production Over Time line graph. Repeat with the latest available year.
    - Period - Calendar Year
    - Period - Fiscal Year
    - With only 2-3 commodities selected.
 
- [ ] Select a state and county without data and verify the expected information is displayed.

#### Explore Data - Nationwide Production Summary and Top Nationwide Locations
- [ ] Verify breakdowns by production type and source are correct as well nationwide locations for the conditions below.
    - Not current Calendar Year
    - Current Calendar Year
    - Not current Fiscal Year
    - Current Fiscal Year

#### Query Data
- [ ] With a selected fiscal year range, verify the data is correct and then for the conditions below. Then repeat with a selected calendar year range. Repeat with a selected monthly range.
    - One Land Type filter
    - One State
    - One Offshore Region
    - One to three Product

### Disbursement
#### Homepage - Yearly Breakdown
- [ ] Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - Breakout - Source 
    - Breakout - Recipient
 
#### Homepage - Monthly Breakdown
- [ ] Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - Period - Most recent 12 months
    - Period - Fiscal Year
    - Period - Calendar Year
    - Breakout - Source
    - Breakout - Recipient
 
#### Source File
- [ ] Check source file links are correct.

#### Explore Data - Map and Detail Card
- [ ] With a fiscal year selected, verify the detail card and Disbursements Over Time are correct for the conditions below. Repeat with the current fiscal year.
    - State with data
    - State without data
    - County with data
    - County without data
    - Offshore Region

#### Explore Data - Nationwide Revenue Summary and Top Nationwide Locations
- [ ] Verify breakdowns by disbursement recipient and source are correct as well nationwide recipients for the conditions below.
    - Not current Fiscal Year
    - Current Fiscal Year

#### Query Data
- [ ] With a selected fiscal year range, verify the data is correct and then for the conditions below. Then repeat with a selected month range.
    - One Recipient
    - One Source
    - One State
    - One to three Commodities if applicable
    - Clear All and change grouping

**Comment by Baymatt** [comment]
Updated the wiki page with the checklist above
