### ISSUE TITLE
Create Revenue by company data review checklist

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#1685]

**Comment by cthomasONRR** [comment]
DRAFT (work in progress)

**Revenue by Company** 	

- [ ] Make sure the downloaded data matches the raw data. Raw data saved [here](https://teams.microsoft.com/l/file/BCAFFDD4-557B-4C74-8405-30E9884403B4?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FData%2FRevenue%20by%20company%2FCY20%20Federal%20Revenues%20by%20Company%20Final.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)

Explore Data - Click on the "Federal revenue by company" link below the map
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year
- [ ] Period - Calendar Year
- [ ] Breakout - Commodity
- [ ] Locality (Map) - State
- [ ] Locality (Map)  - County
- [ ] Locality (Map) - Show Offshore

Query Data - In the "Data Type" category, filter to "Federal revenue by company"
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year
   - [ ] One to three Companies
   - [ ] One to three Revenue Type filters
   - [ ] One to three Commodities
   - [ ] Clear All and change grouping
   - [ ] Downloads matches filtered data

Homepage - Source File
- [ ]  Check source file links are correct.

Download Page
- [ ] Dates and file size are correct for csv and excel

**Comment by lpgoldstein** [comment]
At first glance it looks like the files are slightly different - screenshot below is just 2020. Doing some more digging and I hope that I'm wrong. 
![image](https://user-images.githubusercontent.com/39419003/129775631-40f2aec6-95a5-4bd0-b826-c88039492d17.png)

**Comment by Maroyafaied** [comment]
@mojobnichols could you look into why the numbers are different, could it be how negative numbers are formatted?

**Comment by lpgoldstein** [comment]
@cthomasONRR I'm working on the data within the raw data file so everyone can see what I'm doing but we can delete later

**Comment by cthomasONRR** [comment]
@lpgoldstein and @Maroyafaied It looks like the full file download does not have any negative numbers for 2020. I agree, I think we need Mojo's help!

**Comment by cthomasONRR** [comment]
@mojobnichols , @lpgoldstein , @Maroyafaied 

I'm still not getting the numbers to match up after Mojo's most recent PR.
This is from the downloaded file from the Review Site:
![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/160bc6ad-4c46-41c3-952b-512189bab1f2)

And this is from the Raw data:
![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/6d29c30d-1765-4eb3-8b1d-e11120e5a6d7)

It looks like the negative values are still not getting properly added to the dataset.

**Comment by Maroyafaied** [comment]
@cthomasONRR I don't think @mojobnichols has pushed out his changes yet?

**Comment by cthomasONRR** [comment]
@Maroyafaied I believe he just did:
![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/fedb4182-4320-4602-90d3-6541bc5e1ef6)

**Comment by Maroyafaied** [comment]
@lpgoldstein @cthomasONRR I just checked the data and it's matching now, I didn't do a detailed check , I only checked it against the rawa data.

**Comment by cthomasONRR** [comment]
@Maroyafaied  Here is my revised checklist, based on your suggestion in the PR:

Revenue by Company

- [ ] Make sure the downloaded data matches the raw data. Raw data saved [here]

Explore Data - Click on the "Federal revenue by company" link below the map
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year
   - [ ]  One to three Companies
   - [ ]  Revenue Types within a Company
   - [ ]  One to three Commodities
   - [ ]  Check the Top 10 Companies (highest revenue) to ensure revenue sums and their percent of total is correct
   - [ ]  Check "Other Companies" to ensure that the revenue sum and percent of total is correct

Query Data - In the "Data Type" category, filter to "Federal revenue by company"
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year
   - [ ]  One to three Companies
   - [ ]  One to three Revenue Types
   - [ ]  One to three Commodities
   - [ ]  Clear All and change grouping
   - [ ]  Download matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

**Comment by Maroyafaied** [comment]
@cthomasONRR Looks good, thanks!

**Comment by cthomasONRR** [comment]
@Maroyafaied Great! I just added it to the wiki (https://github.com/ONRR/nrrd/wiki/Releasing-changes-to-production). Closing this issue.
