### ISSUE TITLE
Update the Onboarding Checklist

### ISSUE THREAD

**Issue by eelzi-ONRR** [ONRR/nrrd#2229]
Suggested updates from Erin's onboarding experience:

- [x] Invite XXXX to the oddd-workspace using government email  

* **Problem:** Doesn’t mention Slack anywhere, and it’s the nrrd-workspace  
* **Suggested change:** Invite XXXX to the Slack nrrd-workspace using government email 

- [x] Log in to ZenHub with your GitHub account so that you can view the project planning board
* **Problems:** trying to login without being invited doesn’t work; since you have to be invited, you don’t have to select public repos as is listed on the instructions
* **Suggested change:**  invite XXXX to ZenHub after they have accepted the GitHub invite
* **Suggested change:** move this task to the section on accessing and using GitHub   
* **Suggested change:** Instead of the instructions under the ZenHub item, add a separate item for a ZenHub walk through on how we use it

- [ ] Request Atom & GitHub Desktop
* **Problem:** Getting access to Atom and Github Desktop is listed twice. Once under the development checklist and once under General.
* **Suggested change:** keep them under General only, since that’s where all the other  non-core software is listed

- [x] Get access to any software needed (Axure, Adobe Pro, GitHub Desktop, Atom, Visio, etc.)
* **Problem:** In some cases, the non-core software request options are not the most updated version or the version we use
* **Suggested change:** Either include the version in this list when appropriate (i.e. Axure 10), or add instructions to double check what version is needed before placing the requests

- [ ] add Erin to Team's Folder / Get access to the NRRD Teams Group and Data Display Outlook team calendar
* **Problem:** The folder access is set up so that all Teams members have editor access, so there’s no need to add someone to both the folder and the team. 
* **Suggested change:** remove **add XXXX to Team’s folder**, since adding to the Team will provide the needed access

**Comment by eelzi-ONRR** [comment]
Updated the onboarding checklist on the wiki. Items in this issue with strikethrough were not in the onboarding checklist
