### ISSUE TITLE
Add to the onboarding checklist for data interns & make issues for them

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#904]

**Comment by Maroyafaied** [comment]
@jennmalcolm @mcharg @lpgoldstein below are the items I'm thinking of adding to the onboarding checklist for the data interns. Please review and let me know your thoughts. 

## Data Checklist
- [ ] Learn about the different data sets in our NRRD website by visiting the [download page](https://revenuedata.doi.gov/downloads/)

- [ ] Learn about the different data visuals on our NRRD website by visiting the [Explore Data Page](https://revenuedata.doi.gov/explore)

- [ ] Learn about the [Query data page](https://revenuedata.doi.gov/query-data)

- [ ] Review the [peer reviewing and updating the data checklist](https://github.com/ONRR/nrrd/wiki/Peer-Reviewing-and-Updating-the-Data)

- [ ] Review the {updating data files checklist](https://github.com/ONRR/nrrd/wiki/Releasing-changes-to-production#appendix-things-to-check-while-reviewing-changes)

- [ ] Review previous intern's [data quality script](https://github.com/ONRR/Revdoi-Data-Quality/wiki)
